services:
  - type: web
    name: dewdrop.aicode
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: AXONHUB_SERVER_PORT
        value: 8090
      - key: AXONHUB_DB_DIALECT
        value: postgres
      - key: AXONHUB_DB_DSN
        sync: false
      - key: AXONHUB_LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true
